### ISSUE TITLE
.bazelrc should contain `--enable_bzlmod`

### ISSUE THREAD

**Issue by hzeller** [google/redgrep#14]
Since the build system now works with bzlmod, it should be actively enabled in the .bazelrc, as only bazel 7 assumes this by default. bazel 6 still requires this to be explicitly enabled.

Since I don't know what process you prefer to accept changes (PR ?  googlesource ?), here simply as one-liner patch:

```patch
--- a/.bazelrc
+++ b/.bazelrc
@@ -12,6 +12,8 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+common --enable_bzlmod
+
 # Enable layering check features. Useful on Clang only.
 build --features=layering_check
 # Enable parse headers features. Enforcing that headers are self-contained.
```

**Comment by junyer** [comment]
As discussed over Chat, I appreciate your interest in this project and, moreover, in contributing to this project, but I would prefer to leave it be and let it go gentle into that good night. I currently expect to archive this project whenever LLVM finally removes the MCJIT API and thereby breaks this project forever.
