### ISSUE TITLE
Would like a LLVM_CONFIG environment variable to provide  llvm-config-* instead of just looking for a binary with which()

### ISSUE THREAD

**Issue by hzeller** [google/redgrep#15]
Right now, the llvm-config-17 is extracted from `$PATH` and looking for a binary exactly named `llvm-config-17`

in `internal_configure.bzl` :
```
...
llvm_config = _which(repository_ctx, "llvm-config-17")
...
```

However, depending on how it is installed, the config might just be called `llvm-config` and then requires some hacky workarounds to get `redgrep` to compile (in my case, I had to symbolic link it).

It would be good if the code in `internal_configure.bzl` offer an additional approach and look for an environment variable, say `LLVM_CONFIG` to provide the path to the binary. If that is not set or does not point to a binary, then fall back to the original `which()` attempt to find `llvm-config-17`.

That way, it would just be possible to build, in my case with the `llvm-config` binary, with:
```
LLVM_CONFIG=$(which llvm-config) bazel build ...
```

**Comment by junyer** [comment]
As discussed over Chat, I appreciate your interest in this project and, moreover, in contributing to this project, but I would prefer to leave it be and let it go gentle into that good night. I currently expect to archive this project whenever LLVM finally removes the MCJIT API and thereby breaks this project forever.
