### ISSUE TITLE
Documentation of regex syntax derivative ?

### ISSUE THREAD

**Issue by hzeller** [google/redgrep#16]
Is there a description somewhere about the specific syntax that is supported ? (something like https://github.com/google/re2/wiki/Syntax but since it will probably be shorter might fit in the toplevel README).

There are some specifics uncommon in other dialects, such as `\C` (any byte match ... which I only found reading the [`parser.yy`](https://github.com/google/redgrep/blob/e6a0c3bcd61d52ddac577d34ed783a5e94f9b67c/parser.yy#L252-L254).

**Comment by junyer** [comment]
As discussed over Chat, I appreciate your interest in this project and, moreover, in contributing to this project, but I would prefer to leave it be and let it go gentle into that good night. I currently expect to archive this project whenever LLVM finally removes the MCJIT API and thereby breaks this project forever.
